server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    server_tokens off;

    location = / {
        return 301 $scheme://$host/owntracks/;
    }

    location / {
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    # Canonical OwnTracks entry
    location = /owntracks {
        return 301 /owntracks/;
    }

    location = /owntracks/ {
        auth_basic "My Owntracks";
        auth_basic_user_file /usr/local/owntracks/userdata/htpasswd;
        add_header Set-Cookie "otrauth=wkUBCs8rI6Dhwbal;max-age=86400;path=/;secure;SameSite=None";

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/index.php;
        fastcgi_pass unix:/run/php/php-fpm.sock;
	fastcgi_param REMOTE_USER $remote_user;
    }

    # Frontend SPA
    location ^~ /owntracks/frontend {
        auth_basic $mysite_hascookie;
        auth_basic_user_file /usr/local/owntracks/userdata/htpasswd;

        alias /usr/share/nginx/html/owntracks/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # PHP fallback (otrc.php etc.)
    location ~ \.php$ {
	auth_basic "My Owntracks";
	auth_basic_user_file /usr/local/owntracks/userdata/htpasswd;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php/php-fpm.sock;
	fastcgi_param REMOTE_USER $remote_user;
    }

    # WebSocket
    location /owntracks/ws {
        rewrite ^/owntracks/(.*) /$1 break;
        proxy_read_timeout 120s;
        proxy_pass http://otrecorder:8083;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Recorder static assets
    location ~ /owntracks/(view|static|utils)/ {
        rewrite ^/owntracks/(.*) /$1 break;
        proxy_buffering off;
        proxy_pass http://otrecorder:8083;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Recorder API + views
    location ~ /owntracks/(api|last|map|table)/ {
        auth_basic $mysite_hascookie;
        auth_basic_user_file /usr/local/owntracks/userdata/htpasswd;
        add_header Set-Cookie "otrauth=wkUBCs8rI6Dhwbal;max-age=86400;path=/;secure;SameSite=None";

        rewrite ^/owntracks/(.*) /$1 break;
        proxy_pass http://otrecorder:8083;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # HTTP publish mode
    location /owntracks/pub {
        auth_basic "My OwnTracks";
        auth_basic_user_file /usr/local/owntracks/userdata/htpasswd;
        proxy_pass http://otrecorder:8083/pub;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Limit-U $remote_user;
    }
}

